#!/usr/bin/env python3
"""
Daily Decision Summary - Chief of Staff for Manan Kothari @ Homebase
Runs at 5pm PDT via cron (0 0 * * * UTC), reviews Granola meetings for the day,
and sends a summary to Slack channel D06E4QMHCNN.

Requires: SLACK_BOT_TOKEN environment variable
"""

import os
import sys
import json
import datetime
import requests
from zoneinfo import ZoneInfo

SLACK_CHANNEL = "D06E4QMHCNN"
SLACK_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")

PDT = ZoneInfo("America/Los_Angeles")


def send_slack_message(blocks: list, text: str) -> bool:
    """Send a formatted Slack message using blocks."""
    if not SLACK_TOKEN:
        print("ERROR: SLACK_BOT_TOKEN environment variable not set.")
        print("Please add SLACK_BOT_TOKEN to your Cursor Cloud Agent secrets.")
        print("\nMessage that would be sent:")
        print(text)
        return False

    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={
            "Authorization": f"Bearer {SLACK_TOKEN}",
            "Content-Type": "application/json",
        },
        json={
            "channel": SLACK_CHANNEL,
            "text": text,
            "blocks": blocks,
        },
    )
    result = response.json()
    if not result.get("ok"):
        print(f"Slack API error: {result.get('error', 'Unknown error')}")
        return False
    print("✅ Message sent successfully to Slack!")
    return True


def format_daily_summary(
    date_str: str,
    meetings: list,
    decisions: list,
    action_items: list,
    highlights: str,
) -> tuple[list, str]:
    """Format the daily summary as Slack Block Kit blocks."""

    day_name = datetime.datetime.now(PDT).strftime("%A, %B %-d")
    
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🌅 Your Daily Wrap-Up — {day_name}",
                "emoji": True,
            },
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"*Chief of Staff Summary* | Powered by Granola | {date_str}",
                }
            ],
        },
        {"type": "divider"},
    ]

    if not meetings:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "📭 *No meetings recorded in Granola today.* Sounds like a focused deep-work day — or maybe a well-deserved break! 🙌",
            },
        })
    else:
        # Meetings attended section
        meeting_list = "\n".join([f"• {m}" for m in meetings])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📅 Meetings Today ({len(meetings)})*\n{meeting_list}",
            },
        })
        blocks.append({"type": "divider"})

    if highlights:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*✨ Day Highlights*\n{highlights}",
            },
        })
        blocks.append({"type": "divider"})

    if decisions:
        decisions_text = "\n".join([f"*{i+1}.* {d}" for i, d in enumerate(decisions)])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*🧠 Key Decisions Made*\n{decisions_text}",
            },
        })
        blocks.append({"type": "divider"})

    if action_items:
        actions_text = "\n".join([f"☐ {a}" for a in action_items])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*✅ Action Items & Follow-Ups*\n{actions_text}",
            },
        })
        blocks.append({"type": "divider"})

    blocks.append({
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "_You're doing great, Manan. Crushing it one sprint at a time. 💪 See you tomorrow!_",
        },
    })

    plain_text = f"Daily Summary for {day_name}\n\n"
    if meetings:
        plain_text += "Meetings: " + ", ".join(meetings) + "\n\n"
    if decisions:
        plain_text += "Decisions:\n" + "\n".join(f"- {d}" for d in decisions) + "\n\n"
    if action_items:
        plain_text += "Action Items:\n" + "\n".join(f"- {a}" for a in action_items)

    return blocks, plain_text


# ─── Today's Summary Data (May 27, 2026 — generated by AI from Granola) ───────

# The cron fires at midnight UTC (5pm PDT). Today is May 27, 2026.
# No Granola meetings were recorded for May 27. The most recent day with meetings
# was May 26 (Sprint 2611 Task Refinement). The summary below captures that session's
# output as carry-forward context for May 27.

TODAY_MEETINGS = []  # No meetings on May 27

TODAY_HIGHLIGHTS = (
    "No meetings were recorded in Granola for today (Wednesday, May 27). "
    "Based on your most recent session on May 26 (*[Sprint 2611] Task Refinement*), "
    "here's where things stand heading into tomorrow:"
)

TODAY_DECISIONS = [
    "**Split Sponsored Jobs work into two separate Linear projects** — *Indeed 3LO UX* (entry points 1, 2, 4: job boards, hiring dashboard, integrations page) and *Sponsored Jobs API* (payment flow & job sponsorship). This allows unblocked UX work to move forward immediately while awaiting Indeed's billing/analytics responses.",
    "**3LO UX work can start immediately** — Entry points 1 & 2 are already built (copy updates only needed). The integrations page will be functional once 3LO setup is complete. No outstanding blockers for this workstream.",
    "**Sponsored Jobs API work is blocked** pending two outstanding Indeed responses: (1) $3/API call billing structure confirmation, and (2) campaign analytics requirements. No work should start on the payment flow until clarity is received.",
    "**All new work goes behind a feature flag** until sprint completion assessment — ensuring nothing ships prematurely.",
    "**Use the existing #project-indeed-3lo Slack channel** (not a new one) as the hub for both 3LO UX and Sponsored Jobs API work, since context is already there.",
    "**Redirect URL may need to be split** — Tanner flagged that the account setup flow redirect and token exchange callback are currently sharing one endpoint. Decision to separate them for cleanliness; requires contacting Indeed to register a new redirect URL.",
]

TODAY_ACTION_ITEMS = [
    "**Manan → Linear:** Extract entry points 1, 2, 4 from the Sponsored Jobs API project and move them into the new *Indeed 3LO UX* project.",
    "**Manan → Slack:** Connect the existing *#project-indeed-3lo* channel to the new Indeed 3LO UX project structure.",
    "**Manan → Follow-up with Indeed:** Confirm (a) $3/API call billing structure and (b) whether campaign analytics is a hard requirement — these unblock the Sponsored Jobs API workstream.",
    "**Team (Iszael, Carlo, Tanner, Ugochukwu):** Break down tickets for Indeed 3LO UX work — can start immediately.",
    "**Tanner → Indeed:** Request a separate redirect URL for the account setup flow vs. token exchange callback to keep endpoint responsibilities clean.",
    "**Tanner → Verify with Indeed:** Confirm that employer-bound token acquisition via email + AK code satisfies source claiming requirements.",
    "**Manan → Monitor:** Track token exchange API (built by Andrew) and account setup flow (Tanner's in-progress) — the only missing piece before end-to-end 3LO works.",
]


if __name__ == "__main__":
    now_pdt = datetime.datetime.now(PDT)
    date_str = now_pdt.strftime("%B %-d, %Y at %-I:%M %p PDT")

    blocks, plain_text = format_daily_summary(
        date_str=date_str,
        meetings=TODAY_MEETINGS,
        decisions=TODAY_DECISIONS,
        action_items=TODAY_ACTION_ITEMS,
        highlights=TODAY_HIGHLIGHTS,
    )

    success = send_slack_message(blocks, plain_text)
    sys.exit(0 if success else 1)
