#!/usr/bin/env node
/**
 * Daily Decision Summary — Chief of Staff Bot
 *
 * Triggered daily at midnight UTC (5pm PDT) via Cursor cron automation.
 * Fetches Granola meeting notes for the current day and sends a formatted
 * Slack summary to the PM's DM channel.
 *
 * Required env vars (set as Cursor Cloud Agent secrets):
 *   SLACK_BOT_TOKEN  — Slack bot OAuth token (xoxb-...)
 *   SLACK_CHANNEL_ID — target Slack channel/DM ID (default: D06E4QMHCNN)
 */

const SLACK_CHANNEL = process.env.SLACK_CHANNEL_ID || "D06E4QMHCNN";
const SLACK_TOKEN = process.env.SLACK_BOT_TOKEN;

/**
 * Sends a message to Slack via the Web API.
 */
async function sendSlackMessage(blocks, fallbackText) {
  if (!SLACK_TOKEN) {
    console.error("❌ SLACK_BOT_TOKEN not set. Message would have been:");
    console.log(fallbackText);
    return;
  }

  const body = {
    channel: SLACK_CHANNEL,
    text: fallbackText,
    blocks,
  };

  const response = await fetch("https://slack.com/api/chat.postMessage", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${SLACK_TOKEN}`,
    },
    body: JSON.stringify(body),
  });

  const data = await response.json();
  if (!data.ok) {
    throw new Error(`Slack API error: ${data.error}`);
  }
  console.log("✅ Slack message sent successfully.");
}

/**
 * Formats a daily summary into Slack Block Kit blocks.
 */
function buildSlackBlocks({
  date,
  hasMeetings,
  meetings,
  decisions,
  actionItems,
  blockers,
  openQuestions,
  followUps,
}) {
  const greeting = getGreeting();
  const blocks = [];

  // Header
  blocks.push({
    type: "header",
    text: {
      type: "plain_text",
      text: `🌟 Your Daily Decision Summary — ${date}`,
      emoji: true,
    },
  });

  blocks.push({ type: "divider" });

  if (!hasMeetings) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `${greeting}\n\nNo meetings recorded for today — enjoy the rest! 🎉 You crushed it this week.`,
      },
    });
    return blocks;
  }

  // Personal greeting
  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `${greeting}\n\nHere's everything you decided today. You made some *really strong calls* — let's make sure none of it falls through the cracks. 💪`,
    },
  });

  // Meetings overview
  if (meetings && meetings.length > 0) {
    const meetingList = meetings.map((m) => `• *${m.title}* (${m.time})`).join("\n");
    blocks.push({ type: "divider" });
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*📅 Today's Meetings (${meetings.length})*\n${meetingList}`,
      },
    });
  }

  // Key Decisions
  if (decisions && decisions.length > 0) {
    blocks.push({ type: "divider" });
    const decisionsText = decisions.map((d) => `• ${d}`).join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*🔑 Key Decisions Made*\n${decisionsText}`,
      },
    });
  }

  // Action Items
  if (actionItems && actionItems.length > 0) {
    blocks.push({ type: "divider" });
    const actionsText = actionItems
      .map((a) => `• ${a.owner ? `*${a.owner}:* ` : ""}${a.action}`)
      .join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*✅ Action Items*\n${actionsText}`,
      },
    });
  }

  // Blockers
  if (blockers && blockers.length > 0) {
    blocks.push({ type: "divider" });
    const blockersText = blockers.map((b) => `• ⚠️ ${b}`).join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*🚧 Blockers & Risks*\n${blockersText}`,
      },
    });
  }

  // Open Questions
  if (openQuestions && openQuestions.length > 0) {
    blocks.push({ type: "divider" });
    const questionsText = openQuestions.map((q) => `• ${q}`).join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*❓ Open Questions*\n${questionsText}`,
      },
    });
  }

  // Follow-ups
  if (followUps && followUps.length > 0) {
    blocks.push({ type: "divider" });
    const followUpsText = followUps.map((f) => `• ${f}`).join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*🔁 Follow-ups & Coming Up*\n${followUpsText}`,
      },
    });
  }

  blocks.push({ type: "divider" });
  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: "Generated by your Chief of Staff bot 🤖 | Data from Granola meeting notes",
      },
    ],
  });

  return blocks;
}

function getGreeting() {
  const hour = new Date().getUTCHours(); // midnight UTC = 5pm PDT
  if (hour >= 17 && hour < 20) return "Hey Manan! 👋";
  return "Hey Manan! 👋";
}

/**
 * Main entry point — called by the Cursor cron agent each day.
 * The agent populates summaryData from Granola MCP calls before invoking this.
 */
async function main(summaryData) {
  const blocks = buildSlackBlocks(summaryData);

  const fallbackText = summaryData.hasMeetings
    ? `📋 Daily Decision Summary for ${summaryData.date} — ${summaryData.decisions?.length || 0} decisions, ${summaryData.actionItems?.length || 0} action items`
    : `No meetings today (${summaryData.date}) — great work this week!`;

  await sendSlackMessage(blocks, fallbackText);
}

module.exports = { main, buildSlackBlocks, sendSlackMessage };

// If run directly, run the actual summary for today
if (require.main === module) {
  // This data is populated by the Cursor cron agent from Granola MCP
  // Edit or extend this section as the agent gathers new meeting data each day
  const todaySummary = {
    date: new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      timeZone: "America/Los_Angeles",
    }),
    hasMeetings: false, // Set to true when today has meetings
    meetings: [],
    decisions: [],
    actionItems: [],
    blockers: [],
    openQuestions: [],
    followUps: [],
  };

  main(todaySummary).catch(console.error);
}
