#!/usr/bin/env python3
"""
Daily Chief of Staff Summary — Manan Kothari, PM @ Homebase
Cron: 0 0 * * *  (runs at midnight UTC, summarizes the previous day)

Required secret (add via Cursor Dashboard > Cloud Agents > Secrets):
  SLACK_TOKEN — Slack Bot Token with chat:write scope
"""

import os
import sys
import json
import urllib.request
import urllib.error
from datetime import datetime, timedelta, timezone
from textwrap import dedent

SLACK_CHANNEL = "D06E4QMHCNN"
SLACK_TOKEN = os.environ.get("SLACK_TOKEN", "")


# ---------------------------------------------------------------------------
# Slack helpers
# ---------------------------------------------------------------------------

def _slack_post(payload: dict) -> dict:
    if not SLACK_TOKEN:
        print(
            "ERROR: SLACK_TOKEN is not set.\n"
            "Add your Slack Bot Token (with chat:write scope) to:\n"
            "  Cursor Dashboard > Cloud Agents > Secrets  (key: SLACK_TOKEN)"
        )
        sys.exit(1)

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://slack.com/api/chat.postMessage",
        data=data,
        headers={
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": f"Bearer {SLACK_TOKEN}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        print(f"Network error: {e}")
        sys.exit(1)

    if not result.get("ok"):
        print(f"Slack API error: {result.get('error')}")
        sys.exit(1)

    return result


def send_blocks(fallback: str, blocks: list) -> None:
    result = _slack_post({"channel": SLACK_CHANNEL, "text": fallback, "blocks": blocks})
    print(f"Sent! ts={result.get('ts')}")


def section(text: str) -> dict:
    return {"type": "section", "text": {"type": "mrkdwn", "text": text}}


def header(text: str) -> dict:
    return {"type": "header", "text": {"type": "plain_text", "text": text, "emoji": True}}


def divider() -> dict:
    return {"type": "divider"}


# ---------------------------------------------------------------------------
# Summary builder  — content here is regenerated by the automation each day
# ---------------------------------------------------------------------------

def build_summary(date_str: str) -> tuple[str, list]:
    """
    Returns (fallback_text, blocks).
    The block content below is the synthesised summary for March 13, 2026.
    Each daily run of the automation agent rewrites this function body.
    """

    blocks = [
        header(f"Your Daily Chief of Staff Briefing — {date_str}"),
        divider(),
        section(
            "Hey Manan! :wave: What a *packed* day — 6 meetings, big decisions, "
            "clear momentum. Here's everything you decided, why it matters, and "
            "what needs to happen next. You crushed it today. :muscle:"
        ),
        divider(),

        # ── DECISION 1 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 1 — Appcast Integration Discontinued*"),
        section(
            "*What you decided:* Kill the Appcast job-distribution partnership entirely.\n\n"
            "*Why:* The data was damning — 1.4% applicant conversion rate vs. 15–20% from "
            "your other partners. Zero ROI, just noise in the pipeline.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Andrew (echung)* — Clean up the Appcast XML feed. "
            "Coordinate with Manan on timeline. Target: this sprint.\n"
            "• :white_check_mark: *Manan* — Confirm cleanup is scoped and tracked in backlog."
        ),
        divider(),

        # ── DECISION 2 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 2 — Andrew Becomes Team's Claude AI Specialist*"),
        section(
            "*What you decided:* Designate Andrew as the Hiring team's resident expert "
            "on Claude skills/AI coding tools.\n\n"
            "*Why:* The team is adopting Claude Code and local AI tools — having a dedicated "
            "champion accelerates adoption and quality. It's also a great growth opportunity "
            "for Andrew after completing the Indeed integration.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Andrew (echung)* — Prep and present Claude skills demo "
            "to the full EPD team *by April 10 (next retro)*. Loop in Fadi & Dana on "
            "implementation approaches for the presentation.\n"
            "• :white_check_mark: *Manan* — Add this to Andrew's sprint goals so it's visible."
        ),
        divider(),

        # ── DECISION 3 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 3 — Unit Testing Coverage Report for Frontend*"),
        section(
            "*What you decided:* Commission a frontend unit testing coverage analysis, "
            "led by Carlo, mirroring Jatin's completed backend analysis.\n\n"
            "*Why:* The real incident this sprint (free trial showing paid card) was caused "
            "by gaps in test coverage. You need to know where the frontend is exposed.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Carlo (cferrer)* — Deliver frontend unit testing coverage "
            "report. Identify vulnerable areas and untested scenarios. No hard deadline set — "
            "follow up with Carlo to agree on one.\n"
            "• :white_check_mark: *Manan* — Set a deadline with Carlo in your next 1:1."
        ),
        divider(),

        # ── DECISION 4 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 4 — Demo Screener Ungating (Stretch Goal)*"),
        section(
            "*What you decided:* Explore making the demo screener publicly accessible "
            "(no login required) as a stretch goal for this sprint.\n\n"
            "*Why:* Mass-distributable screener = top-of-funnel experiment at low cost. "
            "With the growth target (doubling revenue), every conversion lever matters. "
            "Security concerns noted — needs grooming before committing.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Dana (dlobo) + Izzy (igonzalez) + Bob (rgao)* — "
            "Scope the security requirements offline this week. Report back before next "
            "sprint planning.\n"
            "• :white_check_mark: *Manan* — Follow up with Dana on scoping outcome by EOW."
        ),
        divider(),

        # ── DECISION 5 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 5 — Application Status State Machine to be Built*"),
        section(
            "*What you decided:* Commit to implementing a proper application status "
            "state machine to fix recurring status transition bugs.\n\n"
            "*Why:* Sharmin flagged another issue today. This is a recurring class of "
            "bugs — the right fix is architectural, not a series of patches.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Bob (rgao) + Jatin (jbhandari)* — Plan the tech debt "
            "work for the hiring public interface and state machine. Add to backlog with "
            "priority level.\n"
            "• :white_check_mark: *Manan* — Confirm with Bob that this is prioritized in "
            "the next grooming session."
        ),
        divider(),

        # ── DECISION 6 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 6 — Sprint Carryover Process Overhaul*"),
        section(
            "*What you decided:* Institute three intervention checkpoints to reduce "
            "sprint carryover: (1) product/design crafting, (2) shaping meetings with "
            "eng input, (3) pre-grooming early callouts.\n\n"
            "*Why:* Carryover is becoming a recurring drag. Goal is dev-done by sprint end, "
            "QA in the following sprint — requires earlier risk surfacing.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Carlo (cferrer)* — Provide a concrete example of a "
            "standardized project brief (MVP vs. stretch goals, Figma checklist). "
            "Share with team before next sprint.\n"
            "• :white_check_mark: *Team* — Flag sprint commitment risks early in standup "
            "(not at sprint end).\n"
            "• :white_check_mark: *Manan* — Formalize the 3-checkpoint process in "
            "documentation; bring to SF offsite discussion."
        ),
        divider(),

        # ── DECISION 7 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 7 — Syndication Speed Metric to be Added*"),
        section(
            "*What you decided:* Add a new metric tracking how fast jobs go live on "
            "Indeed after posting.\n\n"
            "*Why:* Indeed was down for several days this sprint, causing an applicant "
            "volume dip. You need visibility into syndication health in real-time to "
            "catch this faster.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Nelson (ntang) + Manan* — Define and add: "
            "(a) % jobs live on Indeed within 1 hour, "
            "(b) 24-hour syndication success rate. Target: ready for next week's check-in."
        ),
        divider(),

        # ── DECISION 8 ──────────────────────────────────────────────────────
        section("*:dart: DECISION 8 — Q2 Roadmap Session Scheduled*"),
        section(
            "*What you decided:* Hold a Tuesday/Wednesday roadmap session with Dana to "
            "plan Q2 initiatives.\n\n"
            "*Why:* With revenue growth needing to double, you need a crisp Q2 plan across "
            "trial flow, core product, and applicant flow — built from an exhaustive "
            "options list, not rehashed debates.\n\n"
            "*Action Items:*\n"
            "• :white_check_mark: *Manan + Dana (dlobo)* — Each independently prepare "
            "comprehensive initiative lists before the session.\n"
            "• :white_check_mark: *Manan* — Reconvene with Dana Monday afternoon after "
            "she lands (Dolores Park — keep it private/casual)."
        ),
        divider(),

        # ── TOMORROW'S PRIORITIES ────────────────────────────────────────────
        section("*:sunrise: Top 5 Priorities for Monday, March 16*"),
        section(
            "1. :rocket: *Ship the Monday Release* — Google Calendar integration + Manual "
            "Mode + One Click Posting experiment go live. Own the launch narrative.\n"
            "2. :people_holding_hands: *SF Offsite* — New marketing lead joins. Use the "
            "in-person time to align on growth strategy, process improvements, and the "
            "process overhaul decisions from today's retro.\n"
            "3. :bar_chart: *Q2 Roadmap Prep* — Monday afternoon session with Dana "
            "(Dolores Park). Come with your exhaustive initiative list ready.\n"
            "4. :mag: *Demo Screener Scoping Check-In* — Make sure Dana/Izzy/Bob have "
            "started on security scoping.\n"
            "5. :calendar: *Set Carlo's Unit Test Report Deadline* — Don't let this "
            "drift. Lock in a date."
        ),
        divider(),

        section(
            "_You had a genuinely great sprint, Manan. Andrew finished the Indeed integration "
            "after a *year* of work, Google Calendar certification is done, and you shipped "
            "meaningful features. The retro showed a team that's self-aware and ready to "
            "level up. SF is going to be a big week — go make it count. See you tomorrow!_ :tada:"
        ),
    ]

    fallback = f"Chief of Staff Daily Summary — {date_str}: 8 decisions captured with action items."
    return fallback, blocks


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    utc_now = datetime.now(timezone.utc)
    # Cron runs at midnight UTC — summarize the day that just ended
    target_date = utc_now - timedelta(days=1)
    date_str = target_date.strftime("%A, %B %-d, %Y")

    fallback, blocks = build_summary(date_str)
    send_blocks(fallback, blocks)
