#!/usr/bin/env python3
"""
Daily Decision Summary - Chief of Staff Automation
Runs at midnight UTC (5pm PDT / 8pm EDT) and sends a Slack summary
of all Granola meetings and decisions from the day.

Required environment variable:
  SLACK_BOT_TOKEN - Slack bot token (xoxb-...) with chat:write permission
  SLACK_CHANNEL_ID - Slack channel/DM ID (default: D06E4QMHCNN)
  OPENAI_API_KEY - OpenAI API key for summarization (optional, uses built-in logic otherwise)
"""

import os
import json
import datetime
import requests
from typing import Optional

SLACK_CHANNEL_ID = os.environ.get("SLACK_CHANNEL_ID", "D06E4QMHCNN")
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")


def send_slack_message(text: str, blocks: Optional[list] = None) -> dict:
    """Send a message to Slack via the Web API."""
    if not SLACK_BOT_TOKEN:
        raise ValueError(
            "SLACK_BOT_TOKEN environment variable is not set. "
            "Please add it in Cursor Dashboard > Cloud Agents > Secrets."
        )

    payload = {
        "channel": SLACK_CHANNEL_ID,
        "text": text,
    }
    if blocks:
        payload["blocks"] = blocks

    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={
            "Authorization": f"Bearer {SLACK_BOT_TOKEN}",
            "Content-Type": "application/json",
        },
        json=payload,
        timeout=30,
    )
    response.raise_for_status()
    result = response.json()
    if not result.get("ok"):
        raise RuntimeError(f"Slack API error: {result.get('error', 'unknown')}")
    return result


def build_slack_blocks(summary: dict) -> list:
    """Build Slack Block Kit blocks for the daily summary."""
    today = summary["date"]
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📋 Your Daily Decision Brief — {today}",
                "emoji": True,
            },
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": summary["opening"],
            },
        },
        {"type": "divider"},
    ]

    # Meetings overview
    if summary.get("meetings"):
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*📅 Meetings Today ({len(summary['meetings'])})*",
                },
            }
        )
        for meeting in summary["meetings"]:
            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"• *{meeting['time']}* — {meeting['title']} ({meeting['attendees']})",
                    },
                }
            )
        blocks.append({"type": "divider"})

    # Key decisions
    if summary.get("decisions"):
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*🎯 Key Decisions Made Today*",
                },
            }
        )
        for i, decision in enumerate(summary["decisions"], 1):
            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*{i}. {decision['title']}*\n{decision['rationale']}",
                    },
                }
            )
        blocks.append({"type": "divider"})

    # Action items
    if summary.get("action_items"):
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*✅ Action Items & Follow-Ups*",
                },
            }
        )
        action_text = "\n".join(
            f"• {item['owner']}: {item['task']} _{item.get('deadline', '')}_{''}"
            for item in summary["action_items"]
        )
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": action_text},
            }
        )
        blocks.append({"type": "divider"})

    # Closing
    if summary.get("closing"):
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": summary["closing"]},
            }
        )

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "🤖 Generated by your Chief of Staff AI • Powered by Granola + Cursor",
                }
            ],
        }
    )

    return blocks


def build_fallback_text(summary: dict) -> str:
    """Build plain text fallback for the Slack message."""
    lines = [f"📋 Daily Decision Brief — {summary['date']}", ""]
    lines.append(summary.get("opening", ""))
    lines.append("")

    if summary.get("decisions"):
        lines.append("🎯 KEY DECISIONS:")
        for i, d in enumerate(summary["decisions"], 1):
            lines.append(f"{i}. {d['title']}")
            lines.append(f"   → {d['rationale']}")
        lines.append("")

    if summary.get("action_items"):
        lines.append("✅ ACTION ITEMS:")
        for item in summary["action_items"]:
            deadline = f" [{item['deadline']}]" if item.get("deadline") else ""
            lines.append(f"• {item['owner']}: {item['task']}{deadline}")

    return "\n".join(lines)


if __name__ == "__main__":
    # This script is meant to be called by the Cloud Agent automation.
    # The Cloud Agent uses Granola MCP tools to fetch meeting data and
    # OpenAI to generate the summary, then calls send_slack_message().
    print("daily_summary.py — Chief of Staff automation loaded.")
    print(f"Target channel: {SLACK_CHANNEL_ID}")
    print(f"Slack token configured: {'Yes' if SLACK_BOT_TOKEN else 'No — set SLACK_BOT_TOKEN'}")
