#!/usr/bin/env python3
"""
Daily Decision Summary — Slack Sender
Reads today's daily summary markdown and posts it to Slack.
Requires SLACK_BOT_TOKEN environment variable.
"""

import os
import sys
from datetime import datetime, timezone, timedelta

try:
    from slack_sdk import WebClient
    from slack_sdk.errors import SlackApiError
except ImportError:
    print("ERROR: slack-sdk not installed. Run: pip install slack-sdk")
    sys.exit(1)

SLACK_CHANNEL = "D06E4QMHCNN"
PDT = timezone(timedelta(hours=-7))


def build_slack_blocks(summary_path: str) -> list:
    """Convert markdown summary to Slack Block Kit blocks."""
    with open(summary_path, "r") as f:
        content = f.read()

    # Split into sections by H3 headers
    sections = content.split("\n### ")
    header_text = sections[0].strip()

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📋 Daily Decision Summary — {datetime.now(PDT).strftime('%B %d, %Y')}",
            },
        },
        {"type": "divider"},
    ]

    # Add intro
    intro_lines = [l for l in header_text.split("\n") if l.strip() and not l.startswith("#")]
    if intro_lines:
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "\n".join(intro_lines[:3])},
            }
        )

    # Add each decision section (truncated for Slack's 3000 char limit per block)
    for section in sections[1:]:
        lines = section.split("\n")
        title = lines[0].strip()
        body = "\n".join(lines[1:]).strip()

        # Truncate body to Slack's block limit
        if len(body) > 2800:
            body = body[:2800] + "\n_...see full summary in daily_summaries/_"

        blocks.append({"type": "divider"})
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*### {title}*\n{body}"},
            }
        )

    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "_Auto-generated by your AI Chief of Staff via Cursor Cloud Agent • Next summary tomorrow at 5pm PDT_",
                }
            ],
        }
    )

    return blocks


def post_summary_to_slack(summary_path: str) -> bool:
    token = os.environ.get("SLACK_BOT_TOKEN")
    if not token:
        print("ERROR: SLACK_BOT_TOKEN environment variable not set.")
        print("Add it to Cursor Secrets at: Cursor Dashboard > Cloud Agents > Secrets")
        return False

    client = WebClient(token=token)

    try:
        # Read raw markdown for the main text fallback
        with open(summary_path, "r") as f:
            raw_content = f.read()

        # Post with blocks for rich formatting
        blocks = build_slack_blocks(summary_path)

        response = client.chat_postMessage(
            channel=SLACK_CHANNEL,
            text=f"Daily Decision Summary — {datetime.now(PDT).strftime('%B %d, %Y')}",
            blocks=blocks,
            mrkdwn=True,
        )
        print(f"✅ Message sent successfully! ts={response['ts']}")
        return True

    except SlackApiError as e:
        print(f"ERROR posting to Slack: {e.response['error']}")
        return False


if __name__ == "__main__":
    today = datetime.now(PDT).strftime("%Y-%m-%d")
    summary_path = os.path.join(
        os.path.dirname(__file__), "daily_summaries", f"{today}.md"
    )

    if not os.path.exists(summary_path):
        print(f"ERROR: No summary found for today at {summary_path}")
        sys.exit(1)

    success = post_summary_to_slack(summary_path)
    sys.exit(0 if success else 1)
